name: Hurricane Trajectory Analysis App
dependencies:
  - python=3.10
  - pip
  - pip:
    - pactus
    - streamlit
    - matplotlib
    - cartopy
    - yupi
    - numpy
    - pandas
    - xgboost
    - seaborn
    - scikit-learn
    - plotly
